# Generated by Django 6.0 on 2026-04-04 12:54

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core_settings', '0002_initial'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('mobile_no', models.CharField(max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_volunteer', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AdminUser',
            fields=[
            ],
            options={
                'verbose_name': 'Admin',
                'verbose_name_plural': 'Admins',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
        ),
        migrations.CreateModel(
            name='MessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.IntegerField(choices=[(1, 'SMS'), (2, 'Email')])),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('message', models.TextField()),
                ('recipient_email', models.EmailField(blank=True, max_length=254)),
                ('recipient_mobile', models.CharField(blank=True, max_length=20)),
                ('status', models.IntegerField(choices=[(1, 'Success'), (2, 'Failed')])),
                ('error_message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sent_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message Log',
                'verbose_name_plural': 'Message Logs',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='VolunteerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.IntegerField(choices=[(1, 'Guardian'), (2, 'Themself')], default=2)),
                ('first_name_en', models.CharField(blank=True, max_length=50)),
                ('middle_name_en', models.CharField(blank=True, max_length=50)),
                ('last_name_en', models.CharField(blank=True, max_length=50)),
                ('first_name_ar', models.CharField(blank=True, max_length=50)),
                ('middle_name_ar', models.CharField(blank=True, max_length=50)),
                ('last_name_ar', models.CharField(blank=True, max_length=50)),
                ('gender', models.IntegerField(blank=True, choices=[(1, 'Male'), (2, 'Female')], null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('national_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('profession', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=20)),
                ('marital_status', models.IntegerField(blank=True, choices=[(1, 'Single'), (2, 'Married')], null=True)),
                ('volunteer_status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Accepted'), (3, 'Rejected')], default=1)),
                ('has_volunteered_before', models.BooleanField(default=False, verbose_name='Have you volunteered before?')),
                ('experience_description', models.TextField(blank=True, verbose_name='Experience Description')),
                ('work_link', models.URLField(blank=True, verbose_name='Work/Portfolio Link')),
                ('possible_participation_days', models.CharField(blank=True, help_text='Select multiple days (comma separated)', max_length=255)),
                ('possible_participation_time', models.CharField(blank=True, help_text='Select preferred times', max_length=255)),
                ('age_range', models.IntegerField(blank=True, choices=[(1, 'All'), (2, '< 7'), (3, '7 - 12'), (4, '12 - 15'), (5, '15 - 18'), (6, '18 - 28'), (7, '28 - 39'), (8, '39 - 50'), (9, '> 50')], null=True, verbose_name='Age Group')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='users.volunteer')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='events.city')),
                ('joining_reasons', models.ManyToManyField(blank=True, related_name='profiles', to='core_settings.joiningreason')),
                ('skills', models.ManyToManyField(blank=True, related_name='profiles', to='events.skills')),
            ],
        ),
        migrations.CreateModel(
            name='AcceptedVolunteer',
            fields=[
            ],
            options={
                'verbose_name': 'Volunteer',
                'verbose_name_plural': 'Volunteers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.volunteerprofile',),
        ),
        migrations.CreateModel(
            name='VolunteerRegistration',
            fields=[
            ],
            options={
                'verbose_name': 'Volunteer Registration',
                'verbose_name_plural': 'Volunteer Registrations',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.volunteerprofile',),
        ),
        migrations.CreateModel(
            name='VolunteerToken',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('volunteer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth_token', to='users.volunteer')),
            ],
        ),
    ]
