# Generated by Django 5.1.5 on 2026-02-25 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagelog',
            name='message_type',
            field=models.IntegerField(choices=[(1, 'SMS'), (2, 'Email')]),
        ),
        migrations.AlterField(
            model_name='messagelog',
            name='status',
            field=models.IntegerField(choices=[(1, 'Success'), (2, 'Failed')]),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='age_range',
            field=models.IntegerField(blank=True, choices=[(1, 'All'), (2, '< 7'), (3, '7 - 12'), (4, '12 - 15'), (5, '15 - 18'), (6, '18 - 28'), (7, '28 - 39'), (8, '39 - 50'), (9, '> 50')], null=True, verbose_name='Age Group'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(1, 'Male'), (2, 'Female')], null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='marital_status',
            field=models.IntegerField(blank=True, choices=[(1, 'Single'), (2, 'Married')], null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='volunteer_status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Accepted'), (3, 'Rejected')], default=1),
        ),
    ]
