# Generated by Django 6.0 on 2026-01-07 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_adminuser_volunteeruser_user_is_volunteer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='volunteer_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
