# Generated by Django 6.0 on 2026-01-08 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_volunteer_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VolunteerUser',
        ),
        migrations.CreateModel(
            name='AcceptedVolunteer',
            fields=[
            ],
            options={
                'verbose_name': 'Volunteer',
                'verbose_name_plural': 'Volunteers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
        ),
        migrations.CreateModel(
            name='VolunteerRegistration',
            fields=[
            ],
            options={
                'verbose_name': 'Volunteer Registration',
                'verbose_name_plural': 'Volunteer Registrations',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
        ),
    ]
