# Generated by Django 6.0 on 2026-01-12 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_settings', '0001_initial'),
        ('events', '0010_volunteerapplication_check_in_time_and_more'),
        ('users', '0005_delete_volunteeruser_acceptedvolunteer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='volunteers', to='events.city'),
        ),
        migrations.AddField(
            model_name='user',
            name='experience_description',
            field=models.TextField(blank=True, verbose_name='Experience Description'),
        ),
        migrations.AddField(
            model_name='user',
            name='has_volunteered_before',
            field=models.BooleanField(default=False, verbose_name='Have you volunteered before?'),
        ),
        migrations.AddField(
            model_name='user',
            name='joining_reasons',
            field=models.ManyToManyField(blank=True, related_name='volunteers', to='core_settings.joiningreason'),
        ),
        migrations.AddField(
            model_name='user',
            name='possible_participation_days',
            field=models.CharField(blank=True, help_text='Select multiple days (comma separated)', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='possible_participation_time',
            field=models.CharField(blank=True, help_text='Select preferred times', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='work_link',
            field=models.URLField(blank=True, verbose_name='Work/Portfolio Link'),
        ),
    ]
