# Generated by Django 6.0 on 2026-01-12 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_age_range'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email')], max_length=10)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('message', models.TextField()),
                ('recipient_email', models.EmailField(blank=True, max_length=254)),
                ('recipient_mobile', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], max_length=10)),
                ('error_message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sent_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message Log',
                'verbose_name_plural': 'Message Logs',
                'ordering': ['-sent_at'],
            },
        ),
    ]
