# Generated by Django 6.0 on 2026-04-04 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(default='', max_length=100, verbose_name='Name (Arabic)')),
                ('name_en', models.CharField(default='', max_length=100, verbose_name='Name (English)')),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=100, verbose_name='Name (Arabic)')),
                ('name_en', models.CharField(max_length=100, verbose_name='Name (English)')),
            ],
            options={
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=100, verbose_name='Name (Arabic)')),
                ('name_en', models.CharField(max_length=100, verbose_name='Name (English)')),
            ],
            options={
                'verbose_name_plural': 'Skills',
            },
        ),
        migrations.CreateModel(
            name='VolunteerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Accepted'), (3, 'Rejected')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_time', models.DateTimeField(verbose_name='Check-In Time')),
                ('check_out_time', models.DateTimeField(blank=True, null=True, verbose_name='Check-Out Time')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances', to='events.area')),
            ],
            options={
                'verbose_name': 'Attendance Record',
                'verbose_name_plural': 'Attendance Records',
                'ordering': ['-check_in_time'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.IntegerField(choices=[(1, 'Event'), (2, 'Talks'), (3, 'International/VolunteerDay'), (4, 'Ceremony'), (5, 'Programs'), (6, 'ProffisionalVolunteer'), (7, 'Training'), (8, 'Workshop'), (9, 'Initiative'), (10, 'MeetingCycle'), (11, 'Orientation')], default=1)),
                ('location', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('registration_start_datetime', models.DateTimeField(blank=True, null=True)),
                ('registration_end_datetime', models.DateTimeField(blank=True, null=True)),
                ('show_in_home_page', models.BooleanField(default=False)),
                ('send_notification_to_volunteer', models.BooleanField(default=False)),
                ('gender_preference', models.IntegerField(choices=[(1, 'General'), (2, 'Specify Gender')], default=1)),
                ('required_volunteers', models.IntegerField(default=0)),
                ('extra_volunteers', models.IntegerField(default=0, help_text='Extra numbers in the waiting list')),
                ('required_males', models.IntegerField(default=0)),
                ('required_females', models.IntegerField(default=0)),
                ('extra_males', models.IntegerField(default=0, help_text='Extra seats males (waiting list)')),
                ('extra_females', models.IntegerField(default=0, help_text='Extra seats females (waiting list)')),
                ('extra_seats', models.IntegerField(default=0)),
                ('min_participation_time_slots', models.IntegerField(default=1)),
                ('age_range', models.IntegerField(choices=[(1, 'All'), (2, '< 7'), (3, '7 - 12'), (4, '12 - 15'), (5, '15 - 18'), (6, '18 - 28'), (7, '28 - 39'), (8, '39 - 50'), (9, '> 50')], default=1, verbose_name='Target Age Group')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='event_images/')),
                ('proponent_name', models.CharField(blank=True, default='', max_length=255)),
                ('proponent_mobile', models.CharField(blank=True, default='', max_length=20)),
                ('proponent_email', models.EmailField(blank=True, default='', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('areas', models.ManyToManyField(blank=True, related_name='events', to='events.area')),
                ('cities', models.ManyToManyField(blank=True, related_name='events', to='events.city')),
            ],
        ),
    ]
