# Generated by Django 5.1.5 on 2026-02-24 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_admin',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='events', to='events.skills'),
        ),
        migrations.AddField(
            model_name='volunteerapplication',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='events.event'),
        ),
        migrations.AddField(
            model_name='volunteerapplication',
            name='volunteer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='users.volunteer'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='events.volunteerapplication'),
        ),
        migrations.AlterUniqueTogether(
            name='volunteerapplication',
            unique_together={('volunteer', 'event')},
        ),
    ]
