# Generated by Django 5.1.5 on 2026-02-25 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='age_range',
            field=models.IntegerField(choices=[(1, 'All'), (2, '< 7'), (3, '7 - 12'), (4, '12 - 15'), (5, '15 - 18'), (6, '18 - 28'), (7, '28 - 39'), (8, '39 - 50'), (9, '> 50')], default=1, verbose_name='Target Age Group'),
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.IntegerField(choices=[(1, 'Event'), (2, 'Talks'), (3, 'International/VolunteerDay'), (4, 'Ceremony'), (5, 'Programs'), (6, 'ProffisionalVolunteer'), (7, 'Training'), (8, 'Workshop'), (9, 'Initiative'), (10, 'MeetingCycle'), (11, 'Orientation')], default=1),
        ),
        migrations.AlterField(
            model_name='event',
            name='gender_preference',
            field=models.IntegerField(choices=[(1, 'General'), (2, 'Specify Gender')], default=1),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Accepted'), (3, 'Rejected')], default=1),
        ),
    ]
