# Generated by Django 6.0 on 2026-01-06 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerapplication',
            name='checked_in',
            field=models.BooleanField(default=False),
        ),
    ]
