# Generated by Django 6.0 on 2026-01-06 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_volunteerapplication_checked_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('Event', 'Event'), ('Talks', 'Talks'), ('International/VolunteerDay', 'International/VolunteerDay'), ('Ceremony', 'Ceremony'), ('Programs', 'Programs'), ('ProffisionalVolunteer', 'ProffisionalVolunteer'), ('Training', 'Training'), ('Workshop', 'Workshop'), ('Initiative', 'Initiative'), ('MeetingCycle', 'MeetingCycle'), ('Orientation', 'Orientation')], default='Event', max_length=50),
        ),
    ]
