# Generated by Django 6.0 on 2026-01-07 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=100, verbose_name='Name (Arabic)')),
                ('name_en', models.CharField(max_length=100, verbose_name='Name (English)')),
            ],
            options={
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=100, verbose_name='Name (Arabic)')),
                ('name_en', models.CharField(max_length=100, verbose_name='Name (English)')),
            ],
            options={
                'verbose_name_plural': 'Skills',
            },
        ),
        migrations.RemoveField(
            model_name='area',
            name='name',
        ),
        migrations.AddField(
            model_name='area',
            name='name_ar',
            field=models.CharField(default='', max_length=100, verbose_name='Name (Arabic)'),
        ),
        migrations.AddField(
            model_name='area',
            name='name_en',
            field=models.CharField(default='', max_length=100, verbose_name='Name (English)'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_admin',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='extra_seats',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='event_images/'),
        ),
        migrations.AddField(
            model_name='event',
            name='min_participation_time_slots',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='event',
            name='proponent_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='event',
            name='proponent_mobile',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='proponent_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='registration_end_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='registration_start_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='send_notification_to_volunteer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='show_in_home_page',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='events.city'),
        ),
        migrations.AddField(
            model_name='event',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='events', to='events.skills'),
        ),
    ]
