# Generated by Django 6.0 on 2026-01-07 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_city_skills_remove_area_name_area_name_ar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='city',
        ),
        migrations.AddField(
            model_name='event',
            name='cities',
            field=models.ManyToManyField(blank=True, related_name='events', to='events.city'),
        ),
    ]
