# Generated by Django 6.0 on 2026-01-07 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_remove_event_city_event_cities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='event',
        ),
        migrations.AddField(
            model_name='event',
            name='areas',
            field=models.ManyToManyField(blank=True, related_name='events', to='events.area'),
        ),
    ]
