# Generated by Django 6.0 on 2026-01-07 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_remove_area_event_event_areas'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerapplication',
            name='participation_slots',
            field=models.IntegerField(default=1),
        ),
    ]
