# Generated by Django 6.0 on 2026-01-07 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_volunteerapplication_participation_slots'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='extra_females',
            field=models.IntegerField(default=0, help_text='Extra seats females (waiting list)'),
        ),
        migrations.AddField(
            model_name='event',
            name='extra_males',
            field=models.IntegerField(default=0, help_text='Extra seats males (waiting list)'),
        ),
        migrations.AddField(
            model_name='event',
            name='extra_volunteers',
            field=models.IntegerField(default=0, help_text='Extra numbers in the waiting list'),
        ),
        migrations.AddField(
            model_name='event',
            name='gender_preference',
            field=models.CharField(choices=[('GENERAL', 'General'), ('SPECIFIC', 'Specify Gender')], default='GENERAL', max_length=10),
        ),
        migrations.AddField(
            model_name='event',
            name='required_females',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='required_males',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='required_volunteers',
            field=models.IntegerField(default=0),
        ),
    ]
