# Generated by Django 6.0 on 2026-01-08 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_event_extra_females_event_extra_males_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerapplication',
            name='check_in_time',
            field=models.DateTimeField(blank=True, help_text='Set manually when checking in', null=True),
        ),
        migrations.AddField(
            model_name='volunteerapplication',
            name='check_out_time',
            field=models.DateTimeField(blank=True, help_text='Auto-filled when checked out', null=True),
        ),
        migrations.AddField(
            model_name='volunteerapplication',
            name='checked_out',
            field=models.BooleanField(default=False),
        ),
    ]
