# Generated by Django 6.0 on 2026-01-12 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_volunteerapplication_check_in_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='age_range',
            field=models.CharField(choices=[('ALL', 'All'), ('lt_7', '< 7'), ('7_12', '7 - 12'), ('12_15', '12 - 15'), ('15_18', '15 - 18'), ('18_28', '18 - 28'), ('28_39', '28 - 39'), ('39_50', '39 - 50'), ('gt_50', '> 50')], default='ALL', max_length=20, verbose_name='Target Age Group'),
        ),
    ]
