# Generated by Django 5.1.5 on 2026-01-14 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_alter_area_id_alter_city_id_alter_event_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteerapplication',
            name='assigned_area',
        ),
        migrations.RemoveField(
            model_name='volunteerapplication',
            name='check_in_time',
        ),
        migrations.RemoveField(
            model_name='volunteerapplication',
            name='check_out_time',
        ),
        migrations.RemoveField(
            model_name='volunteerapplication',
            name='checked_in',
        ),
        migrations.RemoveField(
            model_name='volunteerapplication',
            name='checked_out',
        ),
    ]
