# Generated by Django 5.1.5 on 2026-01-14 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_remove_volunteerapplication_assigned_area_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteerapplication',
            name='participation_slots',
        ),
    ]
