# Generated by Django 6.0 on 2026-01-08 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0009_event_extra_females_event_extra_males_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ar', models.CharField(max_length=255, verbose_name='Title (Arabic)')),
                ('title_en', models.CharField(max_length=255, verbose_name='Title (English)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Accept Reason',
                'verbose_name_plural': 'Accept Reasons',
            },
        ),
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ar', models.CharField(max_length=255, verbose_name='Title (Arabic)')),
                ('title_en', models.CharField(max_length=255, verbose_name='Title (English)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Clinic',
                'verbose_name_plural': 'Clinics',
            },
        ),
        migrations.CreateModel(
            name='JoiningReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ar', models.CharField(max_length=255, verbose_name='Title (Arabic)')),
                ('title_en', models.CharField(max_length=255, verbose_name='Title (English)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Joining Reason',
                'verbose_name_plural': 'Joining Reasons',
            },
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ar', models.CharField(max_length=255, verbose_name='Title (Arabic)')),
                ('title_en', models.CharField(max_length=255, verbose_name='Title (English)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Profession',
                'verbose_name_plural': 'Professions',
            },
        ),
        migrations.CreateModel(
            name='RejectReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ar', models.CharField(max_length=255, verbose_name='Title (Arabic)')),
                ('title_en', models.CharField(max_length=255, verbose_name='Title (English)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Reject Reason',
                'verbose_name_plural': 'Reject Reasons',
            },
        ),
        migrations.CreateModel(
            name='AreaProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Area',
                'verbose_name_plural': 'Areas',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('events.area',),
        ),
        migrations.CreateModel(
            name='CityProxy',
            fields=[
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('events.city',),
        ),
        migrations.CreateModel(
            name='SkillsProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('events.skills',),
        ),
    ]
