# Generated by Django 6.0 on 2026-04-04 12:54

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_settings', '0001_initial'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Area',
                'verbose_name_plural': 'Areas',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('events.area',),
        ),
        migrations.CreateModel(
            name='CityProxy',
            fields=[
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('events.city',),
        ),
        migrations.CreateModel(
            name='SkillsProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('events.skills',),
        ),
    ]
