"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
For the full list of sdettings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-$u8#a$tmpwf463^m6uc5w+oe=2x_hj)tf$fx@4re6=!&4^+2k@'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third-party apps
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'ckeditor',
    'ckeditor_uploader', # Optional but good for image uploads in editor

    # Local apps
    'users',
    'events',
    'content',
    'core_settings',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

AUTH_USER_MODEL = 'users.User'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'users.authentication.BearerTokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'config.renderers.CustomJSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
}

CORS_ALLOW_ALL_ORIGINS = True  # For development purposes

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Jazzmin Settings
JAZZMIN_SETTINGS = {
    "site_title": "VMS Admin",
    "site_header": "Volunteer Management",
    "site_brand": "VMS",
    "welcome_sign": "Welcome to the Volunteer Management System",
    "search_model": "users.User",
    "show_ui_builder": True,
    "hide_models": ["auth.Group", "authtoken.TokenProxy", "users.User"],
    "order_with_respect_to": ["users", "events", "content", "core_settings"], # Prioritize Users app
    
    # Icons for models and apps (FontAwesome 5)
    "icons": {
        # Users app
        "users.AdminUser": "fas fa-user-shield",
        "users.VolunteerRegistration": "fas fa-user-clock",
        "users.AcceptedVolunteer": "fas fa-user-check",
        "users.MessageLog": "fas fa-envelope-open-text",
        
        # Events app
        "events.Event": "fas fa-calendar-alt",
        "events.VolunteerApplication": "fas fa-clipboard-list",
        "events.City": "fas fa-city",
        "events.Skills": "fas fa-tools",
        "events.Area": "fas fa-map-marked-alt",
        
        # Content app
        "content.Blog": "fas fa-blog",
        "content.Gallery": "fas fa-images",
        "content.Slideshow": "fas fa-photo-video",
        "content.CodeOfConduct": "fas fa-file-contract",
        "content.HomePage": "fas fa-home",
        
        # Core Settings app
        "core_settings.AcceptReason": "fas fa-check-circle",
        "core_settings.JoiningReason": "fas fa-hand-holding-heart",
        "core_settings.RejectReason": "fas fa-times-circle",
        "core_settings.Clinic": "fas fa-clinic-medical",
        "core_settings.Profession": "fas fa-briefcase",
        "core_settings.SkillsProxy": "fas fa-tools",
        "core_settings.AreaProxy": "fas fa-map-marked-alt",
        "core_settings.CityProxy": "fas fa-city",
    },
}
# Trigger reload for Export Functionality (updated 54)

# CKEditor Configuration
CKEDITOR_UPLOAD_PATH = "uploads/"
CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'full',
        'height': 300,
        'width': '100%',
    },
}

# SMS Configuration
SMS_CLIENT_ID = os.environ.get("SMS_CLIENT_ID", "your_client_id")
SMS_CLIENT_SECRET = os.environ.get("SMS_CLIENT_SECRET", "your_client_secret")
SMS_AUTH_URL = os.environ.get("SMS_AUTH_URL", "https://api.sms-provider.com/auth/token")
SMS_SINGLE_URL = os.environ.get("SMS_SINGLE_URL", "https://api.sms-provider.com/send/single")
SMS_BULK_URL = os.environ.get("SMS_BULK_URL", "https://api.sms-provider.com/send/bulk")
SMS_SENDER_ID = os.environ.get("SMS_SENDER_ID", "VMS_ADMIN")

# Email Configuration (Placeholder defaults for SMTP)
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", "admin@vms.com")
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.environ.get("EMAIL_HOST", "smtp.gmail.com")
EMAIL_PORT = int(os.environ.get("EMAIL_PORT", 587))
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "your_email@gmail.com")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "your_password")
