# users/constants.py

GENDER_MALE = 1
GENDER_FEMALE = 2

GENDER_CHOICES = (
    (GENDER_MALE, 'Male'),
    (GENDER_FEMALE, 'Female'),
)

MARITAL_STATUS_SINGLE = 1
MARITAL_STATUS_MARRIED = 2

MARITAL_STATUS_CHOICES = (
    (MARITAL_STATUS_SINGLE, 'Single'),
    (MARITAL_STATUS_MARRIED, 'Married'),
)

VOLUNTEER_STATUS_PENDING = 1
VOLUNTEER_STATUS_ACCEPTED = 2
VOLUNTEER_STATUS_REJECTED = 3

VOLUNTEER_STATUS_CHOICES = (
    (VOLUNTEER_STATUS_PENDING, 'Pending'),
    (VOLUNTEER_STATUS_ACCEPTED, 'Accepted'),
    (VOLUNTEER_STATUS_REJECTED, 'Rejected'),
)

AGE_RANGE_ALL = 1
AGE_RANGE_LT_7 = 2
AGE_RANGE_7_12 = 3
AGE_RANGE_12_15 = 4
AGE_RANGE_15_18 = 5
AGE_RANGE_18_28 = 6
AGE_RANGE_28_39 = 7
AGE_RANGE_39_50 = 8
AGE_RANGE_GT_50 = 9

AGE_RANGE_CHOICES = (
    (AGE_RANGE_ALL, 'All'),
    (AGE_RANGE_LT_7, '< 7'),
    (AGE_RANGE_7_12, '7 - 12'),
    (AGE_RANGE_12_15, '12 - 15'),
    (AGE_RANGE_15_18, '15 - 18'),
    (AGE_RANGE_18_28, '18 - 28'),
    (AGE_RANGE_28_39, '28 - 39'),
    (AGE_RANGE_39_50, '39 - 50'),
    (AGE_RANGE_GT_50, '> 50'),
)

DAYS_SATURDAY = 1
DAYS_SUNDAY = 2
DAYS_MONDAY = 3
DAYS_TUESDAY = 4
DAYS_WEDNESDAY = 5
DAYS_THURSDAY = 6
DAYS_FRIDAY = 7

DAYS_CHOICES = (
    (DAYS_SATURDAY, 'Saturday'),
    (DAYS_SUNDAY, 'Sunday'),
    (DAYS_MONDAY, 'Monday'),
    (DAYS_TUESDAY, 'Tuesday'),
    (DAYS_WEDNESDAY, 'Wednesday'),
    (DAYS_THURSDAY, 'Thursday'),
    (DAYS_FRIDAY, 'Friday'),
)

TIME_MORNING = 1
TIME_EVENING = 2

TIME_CHOICES = (
    (TIME_MORNING, 'Morning'),
    (TIME_EVENING, 'Evening'),
)

MESSAGE_TYPE_SMS = 1
MESSAGE_TYPE_EMAIL = 2

MESSAGE_TYPE_CHOICES = (
    (MESSAGE_TYPE_SMS, 'SMS'),
    (MESSAGE_TYPE_EMAIL, 'Email'),
)

MESSAGE_STATUS_SUCCESS = 1
MESSAGE_STATUS_FAILED = 2

MESSAGE_STATUS_CHOICES = (
    (MESSAGE_STATUS_SUCCESS, 'Success'),
    (MESSAGE_STATUS_FAILED, 'Failed'),
)
