# Generated by Django 6.0 on 2026-01-07 12:59

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ar', models.CharField(max_length=255, verbose_name='Title (Arabic)')),
                ('title_en', models.CharField(max_length=255, verbose_name='Title (English)')),
                ('content_ar', ckeditor.fields.RichTextField(verbose_name='Content (Arabic)')),
                ('content_en', ckeditor.fields.RichTextField(verbose_name='Content (English)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Home Page Content',
            },
        ),
    ]
