# events/constants.py

CATEGORY_EVENT = 1
CATEGORY_TALKS = 2
CATEGORY_VOLUNTEER_DAY = 3
CATEGORY_CEREMONY = 4
CATEGORY_PROGRAMS = 5
CATEGORY_PRO_VOLUNTEER = 6
CATEGORY_TRAINING = 7
CATEGORY_WORKSHOP = 8
CATEGORY_INITIATIVE = 9
CATEGORY_MEETING_CYCLE = 10
CATEGORY_ORIENTATION = 11

CATEGORY_CHOICES = (
    (CATEGORY_EVENT, 'Event'),
    (CATEGORY_TALKS, 'Talks'),
    (CATEGORY_VOLUNTEER_DAY, 'International/VolunteerDay'),
    (CATEGORY_CEREMONY, 'Ceremony'),
    (CATEGORY_PROGRAMS, 'Programs'),
    (CATEGORY_PRO_VOLUNTEER, 'ProffisionalVolunteer'),
    (CATEGORY_TRAINING, 'Training'),
    (CATEGORY_WORKSHOP, 'Workshop'),
    (CATEGORY_INITIATIVE, 'Initiative'),
    (CATEGORY_MEETING_CYCLE, 'MeetingCycle'),
    (CATEGORY_ORIENTATION, 'Orientation'),
)

GENDER_PREF_GENERAL = 1
GENDER_PREF_SPECIFIC = 2

GENDER_PREFERENCE_CHOICES = (
    (GENDER_PREF_GENERAL, 'General'),
    (GENDER_PREF_SPECIFIC, 'Specify Gender'),
)

AGE_RANGE_ALL = 1
AGE_RANGE_LT_7 = 2
AGE_RANGE_7_12 = 3
AGE_RANGE_12_15 = 4
AGE_RANGE_15_18 = 5
AGE_RANGE_18_28 = 6
AGE_RANGE_28_39 = 7
AGE_RANGE_39_50 = 8
AGE_RANGE_GT_50 = 9

AGE_RANGE_CHOICES = (
    (AGE_RANGE_ALL, 'All'),
    (AGE_RANGE_LT_7, '< 7'),
    (AGE_RANGE_7_12, '7 - 12'),
    (AGE_RANGE_12_15, '12 - 15'),
    (AGE_RANGE_15_18, '15 - 18'),
    (AGE_RANGE_18_28, '18 - 28'),
    (AGE_RANGE_28_39, '28 - 39'),
    (AGE_RANGE_39_50, '39 - 50'),
    (AGE_RANGE_GT_50, '> 50'),
)

APP_STATUS_PENDING = 1
APP_STATUS_ACCEPTED = 2
APP_STATUS_REJECTED = 3

APP_STATUS_CHOICES = (
    (APP_STATUS_PENDING, 'Pending'),
    (APP_STATUS_ACCEPTED, 'Accepted'),
    (APP_STATUS_REJECTED, 'Rejected'),
)
